name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t optest121/fastapi-app .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push optest121fastapi-app

      - name: Deploy to Server
        run: |
          ssh ubuntu@54.210.218.25 'docker pull optest121/fastapi-app && docker stop fastapi-container || true && docker rm fastapi-container || true && docker run -d --name fastapi-container -p 8000:8000 optest121/fastapi-app'
